### ISSUE TITLE
VCS directory present: .git

### ISSUE THREAD

**Issue by chorny** [garnier-quentin/perl-libssh#10]
You accidentally packed your repository into distribution. It takes space in CPAN mirrors. Please remove  it.
Build tool for QGARNIER/Libssh-Session-0.7.tar.gz was detected as ExtUtils::MakeMaker.
To remove repository directory you need to:
- Create your distribution for CPAN with your build tool: `make dist` (dmake on Windows).
- Delete old versions from PAUSE

**Comment by garnier-quentin** [comment]
Ok i see i will remove the packages. I can delete it and recreate it ?

**Comment by chorny** [comment]
No need to delete any directory - just configure MANIFEST.SKIP (see EU::MM documentation) to include 'contrib' directory. '.git' will be skipped automatically.

**Comment by garnier-quentin** [comment]
Thanks. I have uploaded a new version 0.8 with that "fix".
