### ISSUE TITLE
simple ssh client example

### ISSUE THREAD

**Issue by iddq** [garnier-quentin/perl-libssh#6]
Hello,

Can you please extend the examples by a simple ssh client that would sends the characters from stdin to the server and vice versa from the server to the stdout?

Thank you.

**Comment by garnier-quentin** [comment]
You have an example here: https://github.com/garnier-quentin/perl-libssh/blob/master/examples/client_execute_simple.pl#L35

**Comment by garnier-quentin** [comment]
Comment the ticket if you still have a problem
