### ISSUE TITLE
undefined symbol: ssh_session_is_known_server with libssh 0.7.x

### ISSUE THREAD

**Issue by brodafly** [garnier-quentin/perl-libssh#7]
Hello!

I tried to build perl-libssh on SLES 15 SP 0 which has 'libssh4-0.7.5' installed (libssh4 is the libssh equivalent for SUSE, no idea why it's named differently). This resulted in the error:
```perl: symbol lookup error: /usr/lib/perl5/site_perl/5.26.1/ppc64le-linux-thread-multi/auto/Libssh/Session/Session.so: undefined symbol: ssh_session_is_known_server```

As far as I could tell `ssh_session_is_known_server()`was added from libssh 8.0 onwards and replaced `ssh_is_server_known()`.

Not sure how this type of issue is usually handled. I saw an example of people changing source code dynamically depending on libssh version used during the build[1]. Should backwards compatibility be part of the perl-libssh project? I haven't investigated if latest versions Net::SSH2 for example are compatible with really old libssh2 versions, but I haven't experienced such issues with it so far.

[1] https://www.redhat.com/archives/libvir-list/2018-November/msg00909.html

**Comment by garnier-quentin** [comment]
Maybe we can do some conditional check. Need to look how to do it properly.

**Comment by garnier-quentin** [comment]
i have found a way to do it. Could you test it ? Sorry for the delay

**Comment by garnier-quentin** [comment]
i have done it for other deprecated functions
